default_platform(:ios)
#puts(sh('git', 'log'))
#commit = last_git_commit
#commit_message = commit[:message]

PRIVATE_KEY = ENV["PRIVATE_KEY"]
BUNDLE_ID = ENV["BUNDLE_ID"]
TEAM_ID = ENV["TEAM_ID"]
VERSION = ENV["VERSION"]
BUILD_NUMBER = ENV["BUILD_NUMBER"]


api_key = app_store_connect_api_key(
    key_id: "57F46WJ5U2",
    issuer_id: "69a6de95-bc84-47e3-e053-5b8c7c11a4d1",
    duration: 1200, 
    in_house: false,
    key_content: PRIVATE_KEY)
platform :ios do 
  lane :upload_to_tf do |options|
    sigh( api_key: api_key )
    
    update_app_identifier(
    	plist_path: "Runner/Info.plist",
  		app_identifier: BUNDLE_ID)
    
    update_code_signing_settings(use_automatic_signing: false, team_id: TEAM_ID, code_sign_identity: "Apple Distribution",  profile_name: lane_context[SharedValues::SIGH_NAME],targets: "Runner")
    
    set_info_plist_value(path: "Runner/Info.plist", key: "ITSAppUsesNonExemptEncryption", value: false)
    increment_version_number(version_number: VERSION)
    increment_build_number( build_number: BUILD_NUMBER)
    build_app(scheme: "Runner", export_options: {
    	method: "app-store",
	signingStyle: "manual",
     	provisioningProfiles: { 
      	BUNDLE_ID => lane_context[SharedValues::SIGH_NAME]
      }
    })      
    upload_to_testflight(
    skip_waiting_for_build_processing: true,
    #changelog: commit_message,
    )

  end
 
end