name: deploy app to testflight
on:
  push:
    branches: [testflight_release]

jobs:
  build_and_deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
      - name: Bundle install
        run: cd ./ios && bundle install
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.17.0"
          channel: "stable"
      - name: Install tools
        run: |
          flutter pub get
          cd ./ios && pod install
      - name: Install bundle
        run: |
          gem install --user-install bundler
          bundle config set path 'vendor/bundle'
          bundle install
      - name: Upload to testflight
        run: 
          bundle exec fastlane ios upload_to_tf

  